version: 2
jobs:

  test:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.7

  # test:
  #   docker:
  #   - image: circleci/python:3.6

    steps:
      - checkout 
      - setup_remote_docker
      - run: make circleci
      - run: make build TARGET=layer
      - run: make build TARGET=lambda
      - run: make deploy TARGET=layer
      - run: make deploy TARGET=lambda ENV=dev
      - run: make test

  deploy:
    docker:
    - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker
      - run: make circleci
      - run: make build TARGET=layer
      - run: make deploy TARGET=lambda
      - run: make deploy TARGET=layer
      - run: make deploy TARGET=lambda

workflows:
  version: 2

  build-test:
    jobs:
      - test:
          # context: luis
          filters:
            branches:
              ignore: master
              # only: master

  deploy-nonprod:
    jobs:
      - deploy:
          context: nonprod
          filters:
            branches:
              only: master

  deploy-prod:
    jobs:
      - deploy:
          context: prod
          filters:
            branches:
              ignore: /.*/
            tags: